// auto-generated by notebook
use std::fs;
use std::path::Path;
use crate::gateway_state::GatewayControlPlane;
pub fn load_control_plane<P: AsRef<Path>>(p: P) -> GatewayControlPlane {
    let path = p.as_ref();
    match fs::read_to_string(path) {
        Ok(txt) => {
            match serde_json::from_str::<GatewayControlPlane>(&txt) {
                Ok(cfg) => cfg,
                Err(e) => {
                    eprintln!("failed to parse control plane {}: {}", path.display(), e);
                    GatewayControlPlane::default()
                }
            }
        }
        Err(e) => {
            eprintln!("control plane file not found ({}): {}", path.display(), e);
            GatewayControlPlane::default()
        }
    }
}
pub fn default_path() -> &'static str {
    "\tmp\art\gateway_control.json"
}
