name: gateway-notebook-ci
on:
  push:
    paths:
      - "gateway/**"
      - ".github/workflows/gateway-notebook-ci.yml"
      - "notebooks/**"
  workflow_dispatch: {}
jobs:
  notebook-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # add jsonschema if you want to validate schemas
          pip install jsonschema
      - name: Run CI check script from artifacts
        run: |
          if [ -f /tmp/art/gateway_ci_check.py ]; then
            python /tmp/art/gateway_ci_check.py --max-p95 1800
          else
            echo "no /tmp/art/gateway_ci_check.py, skipping"
          fi
